openapi: 3.0.0
paths:
  # 날짜별 신체 기록 조회
  /calendar/physicalRecord/{date}:
    get:
      tags:
        - Calendar
      summary: 캘린더 - 날짜별 신체 기록 조회
      parameters:
      # - in: "header"
      #   name: "Authorization"
      #   schema:
      #     type: "string"
      #   required: true
      #   description: "JWT 토큰이 필요합니다"
        - in: path
          name: date
          schema:
            type: string
            default: "2024-01-20"
          required: true
          description: 사용자가 원하는 신체 기록 조회 날짜 
      responses:
        '200':
          description: 날짜별 신체 기록 조회 성공 
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "접근에 성공했습니다."
                  result:
                    type: object
                    properties:
                      physical_record_id: 
                        type: integer
                        example: 1
                      user_id:
                        type: integer
                        example: 1
                      alarmed_date:
                        type: string
                        example: "2024-01-19T15:00:00.000Z"
                      temperture:
                        type: string
                        example: "36.5"
                      weight:
                        type: string
                        example: "60.00"
                      fasting_blood_sugar:
                        type: integer
                        example: 100
                      special_note:
                        type: string
                        example: "좋은 기분"
                      created_at: 
                        type: string
                        example: "2024-02-02T07:43:33.000Z"
                        description: 해당 신체 기록을 기입한 실제 날짜 
                      updated_at:
                        type: string
                        example: "2024-02-02T07:43:33.000Z"
                        description: 해당 신체 기록을 수정한 실제 날짜 
        '404':
          description: 조회 에러 - 해당 날짜에 신체 기록이 없는 경우 
          content:
            application/json: 
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 404
                  message:
                    type: string
                    example: "게시글이 없습니다."
        '500':
          description: 서버 에러 
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccesss:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 500
                  message:
                    type: string
                    example: "서버 에러, 관리자에게 문의 바랍니다."
  
  # 날짜별 신체 기록 삽입
  /calendar/physicalRecord/register/{date}:
    post:
      tags: 
        - Calendar
      summary: 캘린더 - 닐짜별 신체 기록 삽입
      parameters:
      # - in: "header"
      #   name: "Authorization"
      #   schema:
      #     type: "string"
      #   required: true  
      #   description: "JWT 토큰이 필요합니다"    
        - in: path
          name: date
          schema:
            type: string
            default: "2024-01-20"
          required: true
          description: 사용자가 원하는 신체 기록 삽입 날짜 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                temperature:
                  type: number
                  description: 체온
                  example: 36.5
                weight: 
                  type: number
                  description: 체중
                  example: 60.0
                fastingBloodSugar:
                  type: integer
                  description: 공복혈당
                  example: 10
                note:
                  type: string
                  description: 특이사항
                  example: "상쾌한 하루"
      responses:
        '200':
          description: 날짜별 신체 기록 삽입 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "접근에 성공했습니다."
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 500
                  message:
                    type: string
                    example: "서버 에러, 관리자에게 문의 바랍니다."
        '400':
          description: 중복 에러 - 이미 해당 날짜에 신체 기록이 존재
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "요청한 게시글이 이미 존재합니다."
                  

  # 날짜별 신체 기록 삭제
  /calendar/physicalRecord/delete/{date}:
    get:
      tags:
        - Calendar
      summary: 캘린더 - 날짜별 신체 기록 삭제
      parameters:
      # - in: "header"
      #   name: "Authorization"
      #   schema:
      #     type: "string"
      #   required: true    
      #   description: "JWT 토큰이 필요합니다"
        - in: path
          name: date
          schema:
            type: string
            default: "2024-01-20"
          required: true
          description: 사용자가 원하는 신체 기록 삭제 날짜 
      responses:
        '200':
          description: 날짜별 신체 기록 삭제 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "접근에 성공했습니다."
        '500':
          description: 서버 에러 
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 500
                  message:
                    type: string
                    example: "서버 에러, 관리자에게 문의 바랍니다."        
        '404':
          description: 삭제 에러 - 해당 날짜에 신체 기록이 없는 경우
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 404
                  message:
                    type: string
                    example: "게시글이 없습니다."

  # 날짜별 신체 기록 수정 
  /calendar/physicalRecord/update/{date}:
    post:
      tags:
        - Calendar
      summary: 캘린더 - 날짜별 신체 기록 수정        
      parameters:
      # - in: "header"
      #   name: "Authorization"
      #   schema:
      #     type: "string"
      #   required: true    
      #   description: "JWT 토큰이 필요합니다"
        - in: path
          name: date
          schema:
            type: string
            default: "2024-01-20"
          required: true
          description: 사용자가 원하는 신체 기록 수정 날짜
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                temperature:
                  type: number
                  description: 체온
                  example: 36.5
                weight: 
                  type: number
                  description: 체중
                  example: 60.0
                fastingBloodSugar:
                  type: integer
                  description: 공복혈당
                  example: 10
                note:
                  type: string
                  description: 특이사항
                  example: "수정했습니다."        
      responses:
        '200':
          description: 날짜별 신체 기록 수정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true 
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "접근에 성공했습니다."
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 500
                  message:
                    type: string
                    example: "서버 에러, 관리자에게 문의 바랍니다."        
        '404':
          description: 수정 에러 - 해당 날짜에 신체 기록이 없는 경우
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 404
                  message:
                    type: string
                    example: "게시글이 없습니다."        

                        